Naming/AccessorMethodName:
  Enabled: false

Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RaiseArgs:
  Enabled: false

Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
