default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mgc_development

test:
  <<: *default
  database: mgc_test

production:
  <<: *default
  database: mgc_production
  username: mgc
  password: <%= ENV['MGC_DATABASE_PASSWORD'] %>
